IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'BOOK')
BEGIN

	CREATE TABLE BOOK(
		BOOK_ID int IDENTITY(1,1) NOT NULL PRIMARY KEY,
		BOOK_ISBN nvarchar(20) NOT NULL,
		BOOK_TITLE nvarchar(250) NOT NULL,
		BOOK_PUBLISHER nvarchar(250) NOT NULL,
		BOOK_AUTHOR nvarchar(250) NOT NULL,
		BOOK_COVER_IMAGE nvarchar(250) NOT NULL,
		BOOK_SUMMARY nvarchar(MAX) NOT NULL,
		BOOK_FAVORITE BIT NOT NULL DEFAULT(0)
	)
END